export default async (page, baseUrl) => {
 const failures=[];const passed=[];page.on('pageerror',e=>failures.push(e.message));page.on('console',m=>{if(m.type()==='error')failures.push(m.text())});
 const assert=(ok,label)=>{if(!ok)throw new Error(label);passed.push(label)};
 await page.setViewportSize({width:1440,height:900});await page.goto(baseUrl);
 await page.locator('.aml-canvas[data-settled=true]').waitFor();
 assert(await page.locator('.aml-canvas').getAttribute('data-node-count')==='2248','Full 2248 node graph');
 assert(await page.locator('.aml-canvas').getAttribute('data-link-count')==='3119','3119 directed transfers');
 assert(Number(await page.locator('.aml-canvas').getAttribute('data-reciprocal-count'))>=2,'Reciprocal links retained');
 assert(await page.locator('*').count()<1500,'Canvas DOM stays below 1500 elements');
 const search=async gid=>{await page.getByRole('textbox',{name:'Поиск по gid'}).fill(gid);await page.getByRole('button',{name:'Найти',exact:true}).click();await page.locator('.node-gid').filter({hasText:gid}).waitFor()};
 await search('900000000000100001');
 await page.getByRole('button',{name:'Фокус',exact:true}).click();await page.waitForTimeout(700);
 await page.screenshot({path:'qa/aml-selected-1440.png'});
 let box=await page.locator('.aml-canvas').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.locator('.aml-tooltip').waitFor();
 await page.waitForTimeout(250);assert((await page.locator('.aml-tooltip').innerText()).includes('900000000000100001'),'Canvas hover shows exact GID: '+await page.locator('.aml-tooltip').innerText());
 await page.getByRole('button',{name:'Снять выбор клиента'}).click();
 assert(await page.locator('.node-gid').count()===0,'Clear selection resets inspector');
 await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await page.locator('.node-gid').waitFor();
 assert(await page.locator('.node-gid').innerText()==='900000000000100001','Canvas node click updates inspector');
 await page.getByRole('radio',{name:'Связи клиента',exact:true}).click();
 const one=Number(await page.locator('.aml-canvas').getAttribute('data-node-count'));
 await page.getByRole('radio',{name:'4',exact:true}).click();
 const four=Number(await page.locator('.aml-canvas').getAttribute('data-node-count'));
 assert(one===10&&four>=one,'Local 1 to 4 hops');
 await page.getByRole('radio',{name:'Исходящие',exact:true}).click();
 assert(Number(await page.locator('.aml-canvas').getAttribute('data-node-count'))<four,'Directed local traversal');
 await page.getByRole('button',{name:'Цепочки',exact:true}).click();
 assert(await page.getByRole('button',{name:'Цепочки',exact:true}).getAttribute('aria-pressed')==='true','Trace flow toggle');
 await page.getByRole('tab',{name:'Основания',exact:true}).click();await page.getByText('Из чего складывается приоритет').waitFor();passed.push('Inspector evidence tab');
 await page.getByRole('button',{name:'Снять выбор клиента'}).click();
 await search('900000000000100023');await page.getByText(/Граница наблюдения/).first().waitFor();passed.push('Depth 4 caveat');
 await search('900000000000100026');await page.getByRole('radio',{name:'Связи клиента',exact:true}).click();
 assert(await page.locator('.aml-canvas').getAttribute('data-node-count')==='1','Isolated node preserved');
 await page.getByRole('tab',{name:'Переводы',exact:true}).click();await page.getByText('Нет наблюдаемых связей',{exact:true}).waitFor();passed.push('Empty transfers');
 await page.getByRole('textbox',{name:'Поиск по gid'}).fill('123');await page.getByRole('button',{name:'Найти',exact:true}).click();await page.getByText('Клиент не найден',{exact:true}).waitFor();
 assert(await page.locator('.node-gid').innerText()==='900000000000100026','Unknown exact search preserves selection');
 await page.getByRole('button',{name:'Снять выбор клиента'}).click();await page.getByRole('tab',{name:'Граф',exact:true}).click();
 await page.getByRole('button',{name:'Настройки графа',exact:true}).click();
 assert(failures.length===0,'No console/runtime errors');return {passed,failures};
}
