export default async (page, baseUrl) => {
 const errors=[];const passed=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 const assert=(v,label)=>{if(!v)throw new Error(label);passed.push(label)};
 await page.setViewportSize({width:1920,height:1080});await page.goto(baseUrl);await page.locator('.aml-canvas[data-settled=true]').waitFor();
 await page.screenshot({path:'qa/aml-1920.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'1920 no overflow');
 await page.getByRole('button',{name:'Настройки графа',exact:true}).click();
 await page.getByRole('button',{name:'Топ приоритетов',exact:true}).click();
 assert(await page.locator('.aml-canvas').getAttribute('data-node-count')==='20','Top20 preset');
 await page.getByRole('combobox',{name:'Топ по приоритету проверки'}).click();await page.getByRole('option',{name:'50 приоритетов'}).click();
 assert(await page.locator('.aml-canvas').getAttribute('data-node-count')==='50','Top50 selection');
 await page.getByRole('button',{name:'Сбросить фильтры',exact:true}).click();
 await page.getByRole('radio',{name:'Низкий',exact:true}).click();
 const low=Number(await page.locator('.aml-canvas').getAttribute('data-node-count'));assert(low>0&&low<2248,'Low priority filter');
 await page.getByRole('radio',{name:'Высокий',exact:true}).click();
 const high=Number(await page.locator('.aml-canvas').getAttribute('data-node-count'));assert(high>0&&high<2248,'High priority filter');
 await page.getByRole('button',{name:'Сбросить фильтры',exact:true}).click();
 await page.getByRole('spinbutton',{name:'Мин. наблюдаемый оборот, ₸'}).fill('999999999999999');
 await page.getByText('Нет совпадений',{exact:true}).waitFor();passed.push('Empty filter state');
 await page.locator('#graph-settings').getByRole('button',{name:'Сбросить фильтры',exact:true}).click();
 await page.getByRole('button',{name:'Координаторы',exact:true}).click();assert(Number(await page.locator('.aml-canvas').getAttribute('data-node-count'))>0,'Coordinator quick filter');
 await page.getByRole('button',{name:'Сеть исходных',exact:true}).click();assert(Number(await page.locator('.aml-canvas').getAttribute('data-node-count'))>81,'Seed network includes neighbors');
 await page.getByRole('button',{name:'Сбросить фильтры',exact:true}).click();
 await page.getByRole('combobox',{name:'Кластер',exact:true}).click();await page.getByRole('option',{name:'Кластер 0',exact:true}).click();assert(Number(await page.locator('.aml-canvas').getAttribute('data-node-count'))<2248,'Cluster filter');
 await page.getByRole('button',{name:'Сбросить фильтры',exact:true}).click();await page.getByRole('button',{name:'ФИЛЬТРЫ',exact:true}).click();
 await page.getByRole('button',{name:'ГРУППИРОВКА',exact:true}).click();
 await page.locator('.aml-canvas[data-settled=true]').waitFor();
 await page.getByRole('radio',{name:'Роль',exact:true}).click();assert(await page.locator('.aml-canvas').getAttribute('data-settled')==='true','Color change does not restart layout');
 assert(await page.locator('.aml-color-legend').innerText().then(t=>t.includes('Гипотезы ролей')),'Role legend');
 await page.getByRole('radio',{name:'Кластер',exact:true}).click();assert(await page.locator('.aml-color-legend').innerText().then(t=>t.includes('Сообщества')),'Cluster legend');
 await page.getByRole('button',{name:'ОТОБРАЖЕНИЕ',exact:true}).click();await page.getByRole('switch',{name:'Стрелки переводов'}).click();
 assert(await page.locator('.aml-canvas').getAttribute('data-settled')==='true','Arrow setting preserves layout');
 await page.getByRole('slider',{name:'Масштаб узлов'}).focus();await page.keyboard.press('ArrowRight');passed.push('Keyboard node scale slider');
 await page.getByRole('button',{name:'СИЛЫ',exact:true}).click();await page.getByRole('slider',{name:'Отталкивание'}).focus();await page.keyboard.press('ArrowRight');
 await page.getByRole('button',{name:'Перестроить раскладку'}).click();await page.locator('.aml-canvas[data-settled=true]').waitFor();passed.push('Forces and reset');
 await page.screenshot({path:'qa/aml-settings-1920.png'});await page.getByRole('button',{name:'Закрыть настройки графа'}).click();
 await page.setViewportSize({width:1440,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'1440 no overflow');
 assert(errors.length===0,'No console/runtime errors');return {passed,errors,low,high};
}
